package com.unesco.core.entities.journal;

import com.unesco.core.entities.schedule.LessonEntity;

import javax.persistence.*;
import java.util.Date;
import java.util.List;

@Entity
@Table(name="un_visitationConfig")
public class VisitationConfigEntity {
    @Id
    @SequenceGenerator(name = "visitationConfigSequenceGen", sequenceName = "visitationConfigSequenceGen", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "visitationConfigSequenceGen")
    private long id;

    @OneToOne
    @JoinColumn(name = "lesson_id")
    private LessonEntity lesson;
    private boolean isAutoGenerated;

    @ElementCollection
    private List<Date> dates;
    private int value;

    public long getId() {
        return id;
    }
    public void setId(long id) {
        this.id = id;
    }

    public LessonEntity getLesson() {
        return lesson;
    }
    public void setLesson(LessonEntity lesson) {
        this.lesson = lesson;
    }

    public boolean isAutoGenerated() {
        return isAutoGenerated;
    }
    public void setAutoGenerated(boolean autoGenerated) {
        isAutoGenerated = autoGenerated;
    }

    public List<Date> getDates() {
        return dates;
    }
    public void setDates(List<Date> dates) {
        this.dates = dates;
    }

    public int getValue() {
        return value;
    }
    public void setValue(int value) {
        this.value = value;
    }

}
