import {Lesson} from "../shedule/lesson";

export class VisitationConfig {
    id: number;
    lesson: Lesson;
    autoGenerated: boolean;
    dates: Array<Date>;
    value: number;

    constructor() {
        this.id = 0;
        this.lesson = new Lesson();
        this.autoGenerated = true;
        this.dates = new Array<Date>();
        this.value = 1;
    }
}
