create sequence competence_sequence_gen start 1 increment 1;
create sequence department_sequence_gen start 1 increment 1;
create sequence discipline_sequence_gen start 1 increment 1;
create sequence field_of_knowledge_sequence_gen start 1 increment 1;
create sequence file_byte_code_sequence_gen start 1 increment 1;
create sequence file_description_sequence_gen start 1 increment 1;
create sequence group_sequence_gen start 1 increment 1;
create sequence institute_sequence_gen start 1 increment 1;
create sequence lesson_event_sequence_gen start 1 increment 1;
create sequence lesson_sequence_gen start 1 increment 1;
create sequence lesson_type_sequence_gen start 1 increment 1;
create sequence news_sequence_gen start 1 increment 1;
create sequence pair_sequence_gen start 1 increment 1;
create sequence plan_sequence_gen start 1 increment 1;
create sequence point_sequence_gen start 1 increment 1;
create sequence point_type_sequence_gen start 1 increment 1;
create sequence professor_sequence_gen start 1 increment 1;
create sequence role_sequence_gen start 1 increment 1;
create sequence room_sequence_gen start 1 increment 1;
create sequence semester_sequence_gen start 1 increment 1;
create sequence student_sequence_gen start 1 increment 1;
create sequence task_description_sequence_gen start 1 increment 1;
create sequence task_sequence_gen start 1 increment 1;
create sequence user_sequence_gen start 1 increment 1;
create table un_competence (id int8 not null, code varchar(255), description varchar(255), primary key (id));
create table un_department (id int8 not null, name varchar(255), institute_id int8, primary key (id));
create table un_discipline (id int8 not null, name varchar(255), field_of_knowledge_id int8, primary key (id));
create table un_field_of_knowledge (id int8 not null, name varchar(255), primary key (id));
create table un_file_byte_code (id int8 not null, data bytea, file_description_id int8, primary key (id));
create table un_file_description (id int8 not null, file_name varchar(255), file_type varchar(255), primary key (id));
create table un_group (id int8 not null, name varchar(255), department_id int8, primary key (id));
create table un_institute (id int8 not null, name varchar(255), primary key (id));
create table un_lesson (id int8 not null, discipline_id int8, group_id int8, professor_id int8, primary key (id));
create table un_lesson_event (id int8 not null, comment varchar(255), date timestamp, lesson_id int8, point_type_id int8, primary key (id));
create table un_lesson_type (id int8 not null, hours int4 not null, name varchar(255), semester_id int8, primary key (id));
create table un_news (id int8 not null, content text, date timestamp, header varchar(255), image bytea, tags varchar(255), author_id int8, primary key (id));
create table un_pair (id int8 not null, dayofweek varchar(255), pair_number int4 not null, weektype varchar(255), lesson_id int8, room_id int8, primary key (id));
create table un_plan (id int8 not null, index varchar(255), department_id int8, discipline_id int8, primary key (id));
create table un_plan_competence (competence_id int8 not null, plan_id int8 not null, primary key (plan_id, competence_id));
create table un_point (id int8 not null, date timestamp, value int4 not null, pair_id int8, student_id int8, point_type_id int8, primary key (id));
create table un_point_type (id int8 not null, name varchar(255), primary key (id));
create table un_professor (id int8 not null, department_id int8, user_id int8, primary key (id));
create table un_role (id int8 not null, role varchar(255), primary key (id));
create table un_room (id int8 not null, room varchar(255), primary key (id));
create table un_semester (id int8 not null, control_type varchar(255), number int4 not null, plan_id int8, primary key (id));
create table un_student (id int8 not null, group_id int8, user_id int8, primary key (id));
create table un_task_description (id int8 not null, description varchar(255), name varchar(255), status int4 not null, user_id int8, primary key (id));
create table un_task_user (id int8 not null, response varchar(255), status int4 not null, user_id int8, un_task_description int8, primary key (id));
create table un_td_f (task_description_id int8 not null, file_description_id int8 not null, primary key (task_description_id, file_description_id));
create table un_tu_f (task_user_id int8 not null, file_description_id int8 not null, primary key (task_user_id, file_description_id));
create table un_user (id int8 not null, email varchar(255) not null, password varchar(255) not null, photo bytea, userfio varchar(255), username varchar(255) not null, primary key (id));
create table un_user_role (user_id int8 not null, role_id int8 not null, primary key (user_id, role_id));
alter table un_role add constraint UK_6bbg6i0inwkx28mf4l590vsrg unique (role);
alter table un_user add constraint UK_dxwjjgavcrixqm2o3dqifj44u unique (email);
alter table un_user add constraint UK_3kvpwniu5rvsqjy01630qn2ij unique (username);
alter table un_department add constraint FK8vb4b0klqbp9a6c00rexdd77o foreign key (institute_id) references un_institute;
alter table un_discipline add constraint FKjkllc9ud4emq4mcb0k99xyfs2 foreign key (field_of_knowledge_id) references un_field_of_knowledge;
alter table un_file_byte_code add constraint FK3rkn3ae9jtcdbphpdr2khpmsl foreign key (file_description_id) references un_file_description;
alter table un_group add constraint FKdg6ghbt5hjgch3617gaqa4u5a foreign key (department_id) references un_department;
alter table un_lesson add constraint FKpflha7fyi34ggt5etquwles9l foreign key (discipline_id) references un_discipline;
alter table un_lesson add constraint FKrt0da4d7go3syt693onnswwo7 foreign key (group_id) references un_group;
alter table un_lesson add constraint FKe4h7r4j7p9ipj5lyutn3mddob foreign key (professor_id) references un_professor;
alter table un_lesson_event add constraint FKeqmqqodu1250y5e6aopc9xyy2 foreign key (lesson_id) references un_lesson;
alter table un_lesson_event add constraint FKhu4gp04yxgfiwrbrvt3c1jo94 foreign key (point_type_id) references un_point_type;
alter table un_lesson_type add constraint FK349luim9juab2gm91eymytoll foreign key (semester_id) references un_semester;
alter table un_news add constraint FKqm0uk7wvlhtebek4xujsrskh0 foreign key (author_id) references un_user;
alter table un_pair add constraint FK8sjampu2qbvgfuvw222go90ss foreign key (lesson_id) references un_lesson;
alter table un_pair add constraint FKdv25i9nm0ve0de66aer5o5avl foreign key (room_id) references un_room;
alter table un_plan add constraint FK2lsi2ud9c6acepk2k9eubm52e foreign key (department_id) references un_department;
alter table un_plan add constraint FKrcogpp9yiha3dty3jmt6kejov foreign key (discipline_id) references un_discipline;
alter table un_plan_competence add constraint FKg34j750bbuanm0n1cph3qtr6r foreign key (plan_id) references un_competence;
alter table un_plan_competence add constraint FKcexnub0jie4eyp1mklqlvhhs1 foreign key (competence_id) references un_plan;
alter table un_point add constraint FK43bnvi7ysavja5tnk1d1cmejd foreign key (pair_id) references un_pair;
alter table un_point add constraint FK9wcapoja4djyq3d5kss7c8ht6 foreign key (student_id) references un_student;
alter table un_point add constraint FKrknrlmcg911sgxml5fm5vcxqt foreign key (point_type_id) references un_point_type;
alter table un_professor add constraint FK3a8f0kq94lel74x524e9v2tnd foreign key (department_id) references un_department;
alter table un_professor add constraint FKq89b89fwqntx6fedau9dgbnqv foreign key (user_id) references un_user;
alter table un_semester add constraint FKed87rge1todofwej7t89vaywa foreign key (plan_id) references un_plan;
alter table un_student add constraint FKer73ki9fat1msqvf1g555ds9s foreign key (group_id) references un_group;
alter table un_student add constraint FKcylhk1uap4au3h7cil7dqb54e foreign key (user_id) references un_user;
alter table un_task_description add constraint FK2rhws1jgacib2b8yiuf2djc8j foreign key (user_id) references un_user;
alter table un_task_user add constraint FK83khgj99xnneu262ia28wa7ig foreign key (user_id) references un_user;
alter table un_task_user add constraint FKm88rbyonn5lobnq5mxjjdfn6t foreign key (un_task_description) references un_task_description;
alter table un_td_f add constraint FKo73u26wjctp1314fdae0n5bif foreign key (file_description_id) references un_file_description;
alter table un_td_f add constraint FKetf3y9tyir1md2mv3tpnhil9x foreign key (task_description_id) references un_task_description;
alter table un_tu_f add constraint FKmib5bte9tjsnub5spub75nuam foreign key (file_description_id) references un_file_description;
alter table un_tu_f add constraint FK4rx540lqiw50m48gn1vf1qmu0 foreign key (task_user_id) references un_task_user;
alter table un_user_role add constraint FKlsa5unb991hd8jnrgaspxnl4h foreign key (role_id) references un_role;
alter table un_user_role add constraint FKa096td9u9om2vlu4r869737w2 foreign key (user_id) references un_user;