export const LANG_RU_NAME = "ru";

export const LANG_RU_TRANS = {
   "Any": "Любое",
   "username": "Логин",
   "email": "E-mail",
   "roles": "Роли",
   "name": "Название",
   "datecreate": "Дата создания",
   "fieldOfKnowledge": "Раздел знаний",
   "tasks-list" : "Список задач",
   "news-dispatcher-page" : "Управление новостями",
   "journal-page": "Журнал",
   "users": "Пользователи",
   "disciplines": "Дисциплины",
   "institutes": "Институты",
   "departments": "Кафедры",
   "groups": "Группы",
    "ADMIN": "Администратор",
    "STUDENT": "Студент",
    "PROFFESSOR": "Преподаватель",
    "ENGINEER": "Инженер",
    "Processed": "В процессе",
    "Denied": "Отказано",
    "Completed": "Завершено",
    "Checked": "На проверке",
    "Viewed": "Просмотрено",
    "SentToRevision": "Отправлено на доработку",
    "SentToReview": "Отправлено на проверку",
    "department": "Кафедра",
    "institute": "Институт",
    "group": "Группа",
    "userFIO": "ФИО пользователя",
    "password": "Пароль",
    "rooms": "Аудитории",
    "room": "Аудитория",
    "professor": "Преподаватель",
    "PROFESSOR": "Преподаватель",
    "admin ": "Администратор",
    "student ": "Судент",
    "lesson-configurator": "Настройка занятия",
    "settings-page": "Профиль",
    "Answer": "Ответ",
    "Info": "Оповещение",
    "speciality": "Направление",
    "Notice": "Уведомление о прочтении"
};
