package com.unesco.core.managers.journal.journalManager;

import com.unesco.core.dto.account.StudentDTO;
import com.unesco.core.dto.additional.ResponseStatusDTO;
import com.unesco.core.dto.journal.*;
import com.unesco.core.dto.shedule.PairDTO;
import com.unesco.core.managers.journal.journalManager.interfaces.journal.IJournalManager;
import com.unesco.core.managers.journal.lessonEvent.interfaces.lessonEventList.ILessonEventListManager;
import com.unesco.core.utils.PointTypes;
import com.unesco.core.utils.StatusTypes;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.stream.Collectors;

@Component
@Scope("prototype")
public class JournalManager implements IJournalManager {

    @Autowired
    private ILessonEventListManager lessonEventListManager;

    private JournalDTO journal;
    private List<LessonEventDTO> lessonEvents;
    private VisitationConfigDTO visitConfig;

    public JournalManager() {
        journal = new JournalDTO();
    }

    public void Init(JournalDTO journal, List<LessonEventDTO> lessonEvents, VisitationConfigDTO visitConfig)
    {
        this.journal = journal;
        this.lessonEvents = lessonEvents;
        this.visitConfig = visitConfig;
    }

    public void CreateJournal()
    {
        List<PointDTO> points = new ArrayList<>();

        if(!visitConfig.isAutoGenerated() && !visitConfig.getDates().isEmpty()) {
            journal.setDates(visitConfig.getDates());
        }

        // Сортировка дат
        journal.setDates(journal.getDates().stream().sorted().collect(Collectors.toList()));

        int weekNumber = 0;
        Date lastDate = journal.getDates().get(0);
        for (Date date : journal.getDates()) {

            // Для определения четности
            Calendar last = Calendar.getInstance();
            Calendar cur = Calendar.getInstance();
            last.setTime(lastDate);
            cur.setTime(date);
            if(last.get(Calendar.DAY_OF_WEEK) >= cur.get(Calendar.DAY_OF_WEEK) ) {
                weekNumber = weekNumber + 1;
            }

            for (StudentDTO student : journal.getStudents()) {
                for (PairDTO pair : journal.getPairs()) {


                    List<PointDTO> find = this.journal.getJournalCell().stream().
                            filter(o -> o.getStudent().getUser().getId() == student.getUser().getId()
                                    && o.getDate().compareTo(date) == 0
                                    && o.getType().getName().equals(PointTypes.Visitation.toString())
                                    && o.getPair().getId() == pair.getId()
                            )
                            .collect(Collectors.toList());

                    Calendar c = Calendar.getInstance();
                    c.setTime(date);
                    int dayOfWeek = c.get(Calendar.DAY_OF_WEEK);
                    boolean pairEqDay = translateDay(dayOfWeek).equals(pair.getDayofweek());

                    if (find.size() == 0 && pairEqDay) {

                        if(!pair.getWeektype().equals("Все")
                            && (
                                (pair.getWeektype().equals("Чет") && weekNumber % 2 != 0
                                ||
                                pair.getWeektype().equals("Нечет") && weekNumber % 2 == 0)
                                && journal.getPairs().stream().anyMatch(o -> o.getWeektype().equals("Все"))
                                )
                        ) {
                            continue;
                        }
                        PointDTO point = new PointDTO();
                        point.setValue(0);
                        point.setId(0);
                        point.setStudent(student);
                        PointTypeDTO visit = new PointTypeDTO();
                        visit.setName(PointTypes.Visitation.toString());
                        point.setType(visit);
                        point.setDate(date);
                        point.setPair(pair);
                        points.add(point);
                    }

                }
            }
            lastDate = date;
        }

        lessonEventListManager.Init(lessonEvents);
        lessonEventListManager.ApplayFilter(this.journal.getLesson());
        lessonEventListManager.RemoveWithoutDates();
        List<LessonEventDTO> LessonEvents = lessonEventListManager.GetAll();
        // Добавить даты событий если их нет
        List<Date> dates = journal.getDates();
        dates.addAll(LessonEvents.stream().map(o -> o.getDate()).collect(Collectors.toList()));
        journal.setDates(dates);
        // Сортировка дат
        journal.setDates(journal.getDates().stream().distinct().sorted().collect(Collectors.toList()));

        for (StudentDTO student : journal.getStudents()) {
            for (LessonEventDTO currentLessonEvent : LessonEvents) {
                if( !this.journal.getJournalCell().stream().anyMatch(
                        o -> o.getDate().compareTo(currentLessonEvent.getDate()) == 0
                        && o.getType().getId() == currentLessonEvent.getType().getId()
                )) {
                    PointDTO pointLessonEvent = new PointDTO();
                    pointLessonEvent.setValue(0);
                    pointLessonEvent.setId(0);
                    pointLessonEvent.setStudent(student);
                    pointLessonEvent.setType(currentLessonEvent.getType());
                    pointLessonEvent.setDate(currentLessonEvent.getDate());
                    pointLessonEvent.setPair(journal.getPairs().get(0));
                    points.add(pointLessonEvent);
                }
            }
        }

        points.addAll(this.journal.getJournalCell());
        this.journal.setJournalCell(points);

    }

    public List<Date> GetDates()
    {
        return  journal.getDates();
    }

    public ResponseStatusDTO Validate() {
        ResponseStatusDTO responseStatusDTO = new ResponseStatusDTO();
        responseStatusDTO.setStatus(StatusTypes.OK);
        DateFormat df = new SimpleDateFormat("dd.MM.yyyy");

        for(PointDTO cell : this.journal.getJournalCell()) {

            if(cell.getType().getName().equals(PointTypes.Visitation.toString())) {
                if (cell.getValue() > visitConfig.getValue()) {
                    responseStatusDTO.setStatus(StatusTypes.ERROR);
                    responseStatusDTO.addErrors("В ячейке "+cell.getStudent().getUser().getUserFIO()+
                            " "+df.format(cell.getDate())+" указан не верный балл "+cell.getValue()
                            +" из "+visitConfig.getValue()+" ("+PointTypes.Visitation.toString()+")");
                }
            } else {
                LessonEventDTO lessonEventDTO = lessonEvents.stream().filter(o -> o.getType().getId() == cell.getType().getId()).findFirst().get();
                if(cell.getValue() > lessonEventDTO.getMaxValue()) {
                    responseStatusDTO.setStatus(StatusTypes.ERROR);
                    responseStatusDTO.addErrors("В ячейке "+cell.getStudent().getUser().getUserFIO()+
                            " "+df.format(cell.getDate())+" указан не верный балл "+cell.getValue()
                            +" из "+lessonEventDTO.getMaxValue()+" ("+lessonEventDTO.getType().getName()+")");
                }
            }

        }

        return responseStatusDTO;
    }

    public JournalDTO Get() {
        return journal;
    }

    private String translateDay(int dayNum) {
        switch (dayNum) {
            case 1:
                return "Воскресенье";
            case 2:
                return "Понедельник";
            case 3:
                return "Вторник";
            case 4:
                return "Среда";
            case 5:
                return "Четверг";
            case 6:
                return "Пятница";
            case 7:
                return "Суббота";
        }
        return "";
    }

}
