package com.unesco.core.dto.journal;

import com.unesco.core.dto.shedule.LessonDTO;

import java.util.Date;
import java.util.List;

public class VisitationConfigDTO {

    private long id;
    private LessonDTO lesson;
    private boolean autoGenerated;
    private List<Date> dates;
    private int value;

    public long getId() {
        return id;
    }
    public void setId(long id) {
        this.id = id;
    }

    public LessonDTO getLesson() {
        return lesson;
    }
    public void setLesson(LessonDTO lesson) {
        this.lesson = lesson;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }
    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public List<Date> getDates() {
        return dates;
    }
    public void setDates(List<Date> dates) {
        this.dates = dates;
    }

    public int getValue() {
        return value;
    }
    public void setValue(int value) {
        this.value = value;
    }

}
