spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    # Release DB
    url: jdbc:postgresql://192.168.253.8:5432/ict?currentSchema=public
    username: ict
    password: 123456
    driverClassName: org.postgresql.Driver
  http:
    multipart:
      max-file-size: 50Mb
      max-request-size: 50Mb