spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://ictkem.ru:3254/ict?currentSchema=dev
    username: ict
    password: 123456
    driverClassName: org.postgresql.Driver
  http:
    multipart:
      max-file-size: 50Mb
      max-request-size: 50Mb