spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/unesco
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver