spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    # Release DB
    #url: jdbc:postgresql://ictkem.ru:3254/ict?currentSchema=public
    #username: ict
    #password: 123456
    url: jdbc:postgresql://localhost:5432/unesco
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  http:
    multipart:
      max-file-size: 50Mb
      max-request-size: 50Mb